chore(deps-dev): migrate webpack-dev-server from v3 to v4
webpack-cli@4 requires webpack-dev-server@4:
https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0

* Migrate config from v3 to v4:
https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md

* Invoke webpack-dev-server using `webpack serve` instead:
"Error: Cannot find module 'webpack-cli/bin/config-yargs' when use v5"
https://github.com/webpack/webpack-dev-server/issues/2424

* Pass production/development env with `--node-env` instead:
https://github.com/webpack/webpack-cli/blob/master/CHANGELOG.md#450-2021-02-02